### ISSUE TITLE
方便给下这门课的视频资源麽......

### ISSUE THREAD

**Issue by zzyzxb** [invi1998/Algorithms-and-Data-Structures#1]

**Comment by invi1998** [comment]
https://coding.imooc.com/class/71.html
这是我在慕课网买的课，这个是课程链接，你可以去看看，适合你的话就可以入手

**Comment by zzyzxb** [comment]
> https://coding.imooc.com/class/71.html 这是我在慕课网买的课，这是课程链接，你可以去看看，适合你的话就可以入手

好的，谢谢啦
